from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text

class Entry(models.Model):
    """Something the user learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = RichTextField()  # Upgraded for CKEditor
    ai_summary = models.TextField(blank=True, null=True)  # New field to store the AI's summary
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model."""
        # Strip HTML tags just for the string representation preview (optional but helpful)
        preview_text = self.text.replace('<p>', '').replace('</p>', '')
        if len(preview_text) > 50:
            return f"{preview_text[:50]}..."
        else:
            return preview_text


class QuizAttempt(models.Model):
    """A single attempt at an AI-generated quiz for a topic."""
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='quiz_attempts')
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name='quiz_attempts')

    # The questions, generated by the AI. Each item is a dict like:
    # {"question": str, "options": [str, str, str, str], "correct_index": int, "explanation": str}
    questions_data = models.JSONField(default=list)

    # The user's submitted answers. Each item is the option index they picked, or None.
    answers_data = models.JSONField(default=list, blank=True)

    score = models.PositiveIntegerField(default=0)
    total = models.PositiveIntegerField(default=0)
    completed = models.BooleanField(default=False)

    started_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-started_at']

    def __str__(self):
        status = f"{self.score}/{self.total}" if self.completed else "in progress"
        return f"Quiz on {self.topic.text} by {self.user.username} ({status})"

    @property
    def percentage(self):
        if self.total == 0:
            return 0
        return round((self.score / self.total) * 100)